// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/profile-wizard/ConversationalChat.tsx": () => import("../components/mockups/profile-wizard/ConversationalChat.tsx"),
  "./components/mockups/profile-wizard/Current.tsx": () => import("../components/mockups/profile-wizard/Current.tsx"),
  "./components/mockups/profile-wizard/DocumentIntake.tsx": () => import("../components/mockups/profile-wizard/DocumentIntake.tsx"),
  "./components/mockups/profile-wizard/LifeSnapshotTiles.tsx": () => import("../components/mockups/profile-wizard/LifeSnapshotTiles.tsx"),
  "./components/mockups/profile-wizard/SteppedWizard.tsx": () => import("../components/mockups/profile-wizard/SteppedWizard.tsx")
};
