/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Liveness + Qdrant reachability probe.
         *
         *     Default behaviour (no ``include``) is unchanged: confirms Qdrant is
         *     reachable and the scan path's primary collection exists implicitly via
         *     the ``get_collections()`` call.
         *
         *     With ``?include=curriculum`` the probe additionally verifies the
         *     advisory ``settings.curriculum_collection`` is present. Use this in
         *     deployments that have seeded doctrinal PDFs and want a hard signal if
         *     the second collection ever drops out from under them.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan */
        post: operations["scan_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Benefit */
        Benefit: {
            /** Entitlement Id */
            entitlement_id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            estimated_value_chf: components["schemas"]["EstimatedValue"];
            /** Confidence */
            confidence: number;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            /** Required Action */
            required_action: string;
            /** Action Template Id */
            action_template_id?: string | null;
            /** Time Limit Days */
            time_limit_days?: number | null;
            /** Llm Reasoning */
            llm_reasoning: string;
            /** Supporting Doctrine */
            supporting_doctrine?: components["schemas"]["SupportingDoctrine"][];
            /**
             * Disclaimer
             * @default Not a substitute for advice from a Swiss attorney registered with a cantonal bar.
             */
            disclaimer: string;
        };
        /** BenefitReport */
        BenefitReport: {
            /** Generated At */
            generated_at: string;
            /** Profile Hash */
            profile_hash: string;
            /** Benefits */
            benefits: components["schemas"]["Benefit"][];
            /** Suppressed Count */
            suppressed_count: number;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Benefit Id */
            benefit_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
        };
        /** Citation */
        Citation: {
            /**
             * Sr Number
             * @description Fedlex SR number like '220'
             */
            sr_number: string;
            /** Article */
            article: string;
            /** Paragraph */
            paragraph?: string | null;
            /**
             * Canton
             * @default CH
             */
            canton: string;
            /**
             * Language
             * @enum {string}
             */
            language: "de" | "fr" | "it" | "en";
            /** Quote Under 15 Words */
            quote_under_15_words: string;
            /**
             * Effective Date
             * @description Date the article entered into force (Fedlex 'Inkrafttreten'). Used to filter out not-yet-effective law at retrieval time.
             */
            effective_date?: string | null;
            /**
             * Repealed Date
             * @description Date the article was repealed (Fedlex 'Aufhebung'). If null, the article is still in force.
             */
            repealed_date?: string | null;
            /**
             * Score
             * @description Qdrant cosine similarity of the chunk that supports this citation. Set on best_citation in BenefitReport, not on seed Citations.
             */
            score?: number | null;
        };
        /** ContextProfile */
        ContextProfile: {
            /**
             * Canton
             * @enum {string}
             */
            canton: "AG" | "AI" | "AR" | "BE" | "BL" | "BS" | "FR" | "GE" | "GL" | "GR" | "JU" | "LU" | "NE" | "NW" | "OW" | "SG" | "SH" | "SO" | "SZ" | "TG" | "TI" | "UR" | "VD" | "VS" | "ZG" | "ZH";
            /**
             * Language
             * @default de
             * @enum {string}
             */
            language: "de" | "fr" | "it" | "en";
            /**
             * Employment Status
             * @enum {string}
             */
            employment_status: "employee_full_time" | "employee_part_time" | "self_employed" | "business_owner" | "unemployed" | "student" | "retired";
            /** Employer Sector */
            employer_sector?: string | null;
            /** Employment Start Year */
            employment_start_year?: number | null;
            /** Weekly Hours */
            weekly_hours?: number | null;
            /**
             * Housing Status
             * @enum {string}
             */
            housing_status: "tenant" | "owner" | "living_with_family";
            /** Rental Start Year */
            rental_start_year?: number | null;
            /** Lease Reference Rate Tracked */
            lease_reference_rate_tracked?: boolean | null;
            /** Rent Chf Monthly */
            rent_chf_monthly?: number | null;
            /**
             * Household Size
             * @default 1
             */
            household_size: number;
            /**
             * Children Count
             * @default 0
             */
            children_count: number;
            /** Children Ages */
            children_ages?: number[];
            /**
             * Marital Status
             * @enum {string}
             */
            marital_status: "single" | "married" | "registered_partnership" | "divorced" | "widowed";
            /**
             * Income Band Chf
             * @enum {string}
             */
            income_band_chf: "lt_30k" | "30_50k" | "50_80k" | "80_120k" | "120_200k" | "gt_200k";
            /**
             * Has Third Pillar
             * @default false
             */
            has_third_pillar: boolean;
            /** Third Pillar Chf This Year */
            third_pillar_chf_this_year?: number | null;
            /**
             * Business Activity
             * @default none
             * @enum {string}
             */
            business_activity: "none" | "freelance" | "sole_proprietor" | "gmbh" | "ag";
            /** Rd Spend Chf This Year */
            rd_spend_chf_this_year?: number | null;
            /** Commute Km Daily */
            commute_km_daily?: number | null;
            /** Childcare Cost Chf Yearly */
            childcare_cost_chf_yearly?: number | null;
            /**
             * Permit Type
             * @default none
             * @enum {string}
             */
            permit_type: "none" | "B" | "C" | "L" | "F" | "N" | "S" | "G" | "Ci";
            /**
             * Nationality Status
             * @default swiss
             * @enum {string}
             */
            nationality_status: "swiss" | "eu_efta" | "third_country";
            /** Years In Switzerland */
            years_in_switzerland?: number | null;
            /** Recent Life Events */
            recent_life_events?: components["schemas"]["LifeEvent"][];
            /** Free Text Narrative */
            free_text_narrative?: string | null;
        };
        /** EstimatedValue */
        EstimatedValue: {
            /** Min */
            min: number;
            /** Max */
            max: number;
            /**
             * Per
             * @default year
             * @enum {string}
             */
            per: "year" | "one_time" | "month";
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Field */
            field: string;
            /** Value */
            value: string | number | boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LifeEvent */
        LifeEvent: {
            /**
             * Event
             * @enum {string}
             */
            event: "moved_canton" | "had_child" | "got_married" | "got_divorced" | "lost_job" | "started_business" | "started_studies" | "bought_property" | "retired";
            /** Year */
            year: number;
            /** Month */
            month?: number | null;
        };
        /**
         * SupportingDoctrine
         * @description Advisory-only doctrinal pointer surfaced alongside a Benefit.
         *
         *     Sourced from the ``co_curriculum`` Qdrant collection (CO 1-183 +
         *     specialized PDFs). Never a substitute for the SR + article ``Citation``
         *     in ``Benefit.citations`` — the citation contract is unchanged. The
         *     frontend renders these under a "Why this applies" disclosure that is
         *     visually distinct from the binding-authority "Legal basis" block.
         */
        SupportingDoctrine: {
            /**
             * Source Doc
             * @description Filename stem of the doctrinal PDF (e.g. 'co_articles_1_183'). Stable across re-seedings — used as the public identifier.
             */
            source_doc: string;
            /**
             * Chapter
             * @description Optional chapter label from the source document's sidecar metadata. Falls back to None when the contributor did not supply a chapter index.
             */
            chapter?: string | null;
            /**
             * Section
             * @description Optional finer-grained section label inside a chapter (e.g. '§ 12 — Error of fact'). Sourced from the sidecar's section_index. Falls back to None when not supplied.
             */
            section?: string | null;
            /**
             * Score
             * @description Cosine similarity of the supporting chunk (advisory only).
             */
            score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: {
                include?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenefitReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
