/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Liveness + Qdrant reachability probe.
         *
         *     Default behaviour (no flags) is unchanged: confirms Qdrant is
         *     reachable. The primary scan collection's *existence* is implied by
         *     the cluster being up — but absence (or an empty collection) is a
         *     silent killer for ``/scan`` (0 benefits, HTTP 200), so:
         *
         *     With ``?deep=1`` the probe additionally verifies that
         *     ``settings.qdrant_collection`` exists **and** holds ``> 0`` points.
         *     Returns 503 with a precise reason (``collection_missing`` /
         *     ``collection_empty``) so operators pointing the backend at a fresh
         *     or wrong cluster fail fast instead of debugging a "scan returns
         *     nothing" mystery.
         *
         *     With ``?include=curriculum`` the probe additionally verifies the
         *     advisory ``settings.curriculum_collection`` is present. Use this in
         *     deployments that have seeded doctrinal PDFs and want a hard signal if
         *     the second collection ever drops out from under them.
         *
         *     The two flags compose: ``?deep=1&include=curriculum`` runs both.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan */
        post: operations["scan_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_users__user_id__profile_get"];
        put?: never;
        /**
         * Upsert Profile
         * @description Create or update a stored user profile.
         *
         *     Idempotent: re-posting the same profile only bumps ``last_seen_at``.
         *     Setting ``notify_enabled=False`` opts the user out of the nightly
         *     sweep without dropping their stored history (so a re-opt-in keeps
         *     diffing from the last known state).
         */
        post: operations["upsert_profile_users__user_id__profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/scans/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Scan
         * @description Return the most-recent persisted sweep report for this user.
         *
         *     404 when the user exists but has no sweep yet (e.g. profile was
         *     posted seconds ago and the nightly job hasn't fired). The frontend
         *     treats this as "loading — sweep pending" rather than an error.
         */
        get: operations["get_latest_scan_users__user_id__scans_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alerts */
        get: operations["get_alerts_users__user_id__alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/alerts/{alert_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Alert Read
         * @description Mark one alert as read. Idempotent: 204 whether the alert was
         *     unread, already read, or doesn't exist for this user. We expose
         *     ``alerts_exists`` checking via :func:`storage.alert_exists` so the
         *     handler can still return 404 when the alert truly isn't visible
         *     to this user — that's the case the frontend wants to surface, not
         *     "already read".
         */
        post: operations["mark_alert_read_users__user_id__alerts__alert_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audits/agent-backed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Audit Agent Backed
         * @description Aggregate provenance over every persisted scan in the database.
         *
         *     Counts every ``Benefit.agent_provenance`` across every persisted
         *     ``BenefitReport``, not just the latest report per user. Filters
         *     (``since``, ``entitlement_id``) and the ``details`` drill-down
         *     mode mirror the CLI's flags (``--since``, ``--entitlement-id``,
         *     ``--details``) so the HTTP and cron interfaces cannot drift.
         */
        get: operations["admin_audit_agent_backed_admin_audits_agent_backed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentProvenance
         * @description Structured provenance record attached to every Claude call output.
         *
         *     Persisted with each verified ``Benefit`` (so historical scans can be
         *     audited) and emitted as a single-line ``claude_call`` log event (so
         *     even non-persisted call sites — ``/chat`` — leave an audit trail).
         *
         *     ``agent_backed`` is the headline signal: it is True iff the call was
         *     routed through the managed-agents API *and* the resulting session
         *     actually emitted at least one ``agent.tool_use`` or
         *     ``agent.mcp_tool_use`` event. A ``sessions.events`` call that never
         *     used a tool is still ``agent_backed=False`` — that's the whole point
         *     of the audit.
         */
        AgentProvenance: {
            /**
             * Call Kind
             * @description Which Anthropic surface produced this output. 'messages.create' is the legacy completion path; 'sessions.events' is the managed-agents path.
             * @enum {string}
             */
            call_kind: "messages.create" | "sessions.events";
            /**
             * Agent Backed
             * @description True iff call_kind=='sessions.events' AND the session emitted ≥1 agent.tool_use or agent.mcp_tool_use event.
             */
            agent_backed: boolean;
            /**
             * Model
             * @description Claude model identifier used for the call.
             */
            model: string;
            /**
             * Latency Ms
             * @description Wall-clock latency of the call.
             */
            latency_ms: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Agent Id
             * @description Managed agent ID (None on the messages.create path).
             */
            agent_id?: string | null;
            /**
             * Agent Version
             * @description Pinned agent version, if any.
             */
            agent_version?: number | null;
            /**
             * Session Id
             * @description Managed-agents session ID, if any.
             */
            session_id?: string | null;
            /**
             * Environment Id
             * @description Managed-agents environment ID, if any.
             */
            environment_id?: string | null;
            /**
             * Tools Offered
             * @description Tool / toolset names declared on the agent at session creation. Empty on the messages.create path.
             */
            tools_offered?: string[];
            /**
             * Tool Use Count
             * @description Number of agent.tool_use events observed in the stream.
             * @default 0
             */
            tool_use_count: number;
            /**
             * Mcp Tool Use Count
             * @description Number of agent.mcp_tool_use events observed in the stream.
             * @default 0
             */
            mcp_tool_use_count: number;
            /**
             * Mcp Servers Invoked
             * @description Names of MCP servers whose tools were actually invoked.
             */
            mcp_servers_invoked?: string[];
        };
        /**
         * Alert
         * @description One row of the ``alerts`` table.
         *
         *     ``alert_id`` is a deterministic UUID5 derived from
         *     ``(user_id, scan_at, kind, entitlement_id)`` so re-running a sweep
         *     over the same scan + diff is idempotent — the second insert is a
         *     no-op rather than a duplicate inbox entry.
         */
        Alert: {
            /** Alert Id */
            alert_id: string;
            /** User Id */
            user_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "NEW" | "GONE" | "UPDATED";
            /** Entitlement Id */
            entitlement_id: string;
            /** Created At */
            created_at: string;
            /** Read At */
            read_at?: string | null;
            payload: components["schemas"]["AlertPayload"];
        };
        /**
         * AlertList
         * @description List wrapper so the openapi-typescript client gets a named type.
         */
        AlertList: {
            /** Alerts */
            alerts: components["schemas"]["Alert"][];
        };
        /**
         * AlertPayload
         * @description Self-contained snapshot of the entitlement an alert refers to.
         *
         *     Stored as JSON inside the ``alerts`` row — see module docstring for
         *     why this is a copy rather than a foreign key.
         */
        AlertPayload: {
            /** Entitlement Id */
            entitlement_id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Estimated Value Chf Min */
            estimated_value_chf_min: number;
            /** Estimated Value Chf Max */
            estimated_value_chf_max: number;
            /** Previous Estimated Value Chf Min */
            previous_estimated_value_chf_min?: number | null;
            /** Previous Estimated Value Chf Max */
            previous_estimated_value_chf_max?: number | null;
            /** Changed Citations */
            changed_citations?: string[];
            /** Fedlex Amendment Date */
            fedlex_amendment_date?: string | null;
        };
        /** Benefit */
        Benefit: {
            /** Entitlement Id */
            entitlement_id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            estimated_value_chf: components["schemas"]["EstimatedValue"];
            /** Confidence */
            confidence: number;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            /** Required Action */
            required_action: string;
            /** Action Template Id */
            action_template_id?: string | null;
            /** Time Limit Days */
            time_limit_days?: number | null;
            /** Llm Reasoning */
            llm_reasoning: string;
            /** Supporting Doctrine */
            supporting_doctrine?: components["schemas"]["SupportingDoctrine"][];
            /** @description Provenance of the Claude call that produced this benefit's verification. agent_backed=False on every legacy messages.create call site (Task #26 will flip these). */
            agent_provenance?: components["schemas"]["AgentProvenance"] | null;
            /**
             * Disclaimer
             * @default Not a substitute for advice from a Swiss attorney registered with a cantonal bar.
             */
            disclaimer: string;
        };
        /** BenefitReport */
        BenefitReport: {
            /** Generated At */
            generated_at: string;
            /** Profile Hash */
            profile_hash: string;
            /** Benefits */
            benefits: components["schemas"]["Benefit"][];
            /** Suppressed Count */
            suppressed_count: number;
            /**
             * Pending Corpus Backfill
             * @default 0
             */
            pending_corpus_backfill: number;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Benefit Id */
            benefit_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            agent_provenance?: components["schemas"]["AgentProvenance"] | null;
        };
        /** Citation */
        Citation: {
            /**
             * Sr Number
             * @description Fedlex SR number like '220'
             */
            sr_number: string;
            /** Article */
            article: string;
            /** Paragraph */
            paragraph?: string | null;
            /**
             * Canton
             * @default CH
             */
            canton: string;
            /**
             * Language
             * @enum {string}
             */
            language: "de" | "fr" | "it" | "en";
            /** Quote Under 15 Words */
            quote_under_15_words: string;
            /**
             * Effective Date
             * @description Date the article entered into force (Fedlex 'Inkrafttreten'). Used to filter out not-yet-effective law at retrieval time.
             */
            effective_date?: string | null;
            /**
             * Repealed Date
             * @description Date the article was repealed (Fedlex 'Aufhebung'). If null, the article is still in force.
             */
            repealed_date?: string | null;
            /**
             * Score
             * @description Qdrant cosine similarity of the chunk that supports this citation. Set on best_citation in BenefitReport, not on seed Citations.
             */
            score?: number | null;
        };
        /** ContextProfile */
        ContextProfile: {
            /**
             * Canton
             * @enum {string}
             */
            canton: "AG" | "AI" | "AR" | "BE" | "BL" | "BS" | "FR" | "GE" | "GL" | "GR" | "JU" | "LU" | "NE" | "NW" | "OW" | "SG" | "SH" | "SO" | "SZ" | "TG" | "TI" | "UR" | "VD" | "VS" | "ZG" | "ZH";
            /**
             * Language
             * @default de
             * @enum {string}
             */
            language: "de" | "fr" | "it" | "en";
            /**
             * Employment Status
             * @enum {string}
             */
            employment_status: "employee_full_time" | "employee_part_time" | "self_employed" | "business_owner" | "unemployed" | "student" | "retired";
            /** Employer Sector */
            employer_sector?: string | null;
            /** Employment Start Year */
            employment_start_year?: number | null;
            /** Weekly Hours */
            weekly_hours?: number | null;
            /**
             * Housing Status
             * @enum {string}
             */
            housing_status: "tenant" | "owner" | "living_with_family";
            /** Rental Start Year */
            rental_start_year?: number | null;
            /** Lease Reference Rate Tracked */
            lease_reference_rate_tracked?: boolean | null;
            /** Rent Chf Monthly */
            rent_chf_monthly?: number | null;
            /**
             * Household Size
             * @default 1
             */
            household_size: number;
            /**
             * Children Count
             * @default 0
             */
            children_count: number;
            /** Children Ages */
            children_ages?: number[];
            /**
             * Marital Status
             * @enum {string}
             */
            marital_status: "single" | "married" | "registered_partnership" | "divorced" | "widowed";
            /**
             * Income Band Chf
             * @enum {string}
             */
            income_band_chf: "lt_30k" | "30_50k" | "50_80k" | "80_120k" | "120_200k" | "gt_200k";
            /**
             * Has Third Pillar
             * @default false
             */
            has_third_pillar: boolean;
            /** Third Pillar Chf This Year */
            third_pillar_chf_this_year?: number | null;
            /**
             * Business Activity
             * @default none
             * @enum {string}
             */
            business_activity: "none" | "freelance" | "sole_proprietor" | "gmbh" | "ag";
            /** Rd Spend Chf This Year */
            rd_spend_chf_this_year?: number | null;
            /** Commute Km Daily */
            commute_km_daily?: number | null;
            /** Childcare Cost Chf Yearly */
            childcare_cost_chf_yearly?: number | null;
            /**
             * Permit Type
             * @default none
             * @enum {string}
             */
            permit_type: "none" | "B" | "C" | "L" | "F" | "N" | "S" | "G" | "Ci";
            /**
             * Nationality Status
             * @default swiss
             * @enum {string}
             */
            nationality_status: "swiss" | "eu_efta" | "third_country";
            /** Years In Switzerland */
            years_in_switzerland?: number | null;
            /** Recent Life Events */
            recent_life_events?: components["schemas"]["LifeEvent"][];
            /** Free Text Narrative */
            free_text_narrative?: string | null;
        };
        /** EstimatedValue */
        EstimatedValue: {
            /** Min */
            min: number;
            /** Max */
            max: number;
            /**
             * Per
             * @default year
             * @enum {string}
             */
            per: "year" | "one_time" | "month";
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Field */
            field: string;
            /** Value */
            value: string | number | boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LifeEvent */
        LifeEvent: {
            /**
             * Event
             * @enum {string}
             */
            event: "moved_canton" | "had_child" | "got_married" | "got_divorced" | "lost_job" | "started_business" | "started_studies" | "bought_property" | "retired";
            /** Year */
            year: number;
            /** Month */
            month?: number | null;
        };
        /**
         * SupportingDoctrine
         * @description Advisory-only doctrinal pointer surfaced alongside a Benefit.
         *
         *     Sourced from the ``co_curriculum`` Qdrant collection (CO 1-183 +
         *     specialized PDFs). Never a substitute for the SR + article ``Citation``
         *     in ``Benefit.citations`` — the citation contract is unchanged. The
         *     frontend renders these under a "Why this applies" disclosure that is
         *     visually distinct from the binding-authority "Legal basis" block.
         */
        SupportingDoctrine: {
            /**
             * Source Doc
             * @description Filename stem of the doctrinal PDF (e.g. 'co_articles_1_183'). Stable across re-seedings — used as the public identifier.
             */
            source_doc: string;
            /**
             * Chapter
             * @description Optional chapter label from the source document's sidecar metadata. Falls back to None when the contributor did not supply a chapter index.
             */
            chapter?: string | null;
            /**
             * Section
             * @description Optional finer-grained section label inside a chapter (e.g. '§ 12 — Error of fact'). Sourced from the sidecar's section_index. Falls back to None when not supplied.
             */
            section?: string | null;
            /**
             * Score
             * @description Cosine similarity of the supporting chunk (advisory only).
             */
            score: number;
        };
        /**
         * UserProfileUpsert
         * @description Request body for ``POST /users/{user_id}/profile``.
         */
        UserProfileUpsert: {
            profile: components["schemas"]["ContextProfile"];
            /**
             * Notify Enabled
             * @default true
             */
            notify_enabled: boolean;
        };
        /**
         * UserRecord
         * @description One row of the ``users`` table — what the API returns and stores.
         */
        UserRecord: {
            /** User Id */
            user_id: string;
            profile: components["schemas"]["ContextProfile"];
            /**
             * Notify Enabled
             * @default true
             */
            notify_enabled: boolean;
            /** Created At */
            created_at: string;
            /** Last Seen At */
            last_seen_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: {
                include?: string | null;
                deep?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenefitReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_users__user_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_profile_users__user_id__profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_scan_users__user_id__scans_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenefitReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alerts_users__user_id__alerts_get: {
        parameters: {
            query?: {
                unread_only?: boolean;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_alert_read_users__user_id__alerts__alert_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_audit_agent_backed_admin_audits_agent_backed_get: {
        parameters: {
            query?: {
                /** @description ISO-8601 timestamp; only reports generated at or after this instant are counted. */
                since?: string | null;
                /** @description Restrict to a single entitlement — the drill-down mode auditors use to answer 'was THIS verification agent-backed?'. */
                entitlement_id?: string | null;
                /** @description Include the full per-verification provenance list under ``records``. Off by default so the headline call stays cheap. */
                details?: boolean;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
